import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import type { ReactNode } from "react";
import { Providers } from "@/app/providers";
import { Header } from "@/components/header";
import { cn } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "flex min-h-screen flex-col antialiased",
          geistSans.variable,
          geistMono.variable,
        )}
      >
        <Providers>
          <Header />
          <div className="flex min-h-0 flex-1 flex-col *:only:flex-1">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
